### ISSUE TITLE
TV episodes not synchronised

### ISSUE THREAD

**Issue by f0o** [Tolriq/Yatse2#2]
Hi,

First of all it's a great remote and I really consider getting the unlock to support your efforts.

The only thing that keeps me from it is that although I see all shows, it keeps showing 0 episodes for them.

Any pointers on how I could debug this?

**Comment by f0o** [comment]
Correction; it seems like i need to sync every show manually... Is there any way to have it sync all of them at once?

**Comment by Tolriq** [comment]
Well I guess you are talking about android Yatse so 100% unrelated to this....

http://yatse.tv/redmine/projects/yatse/knowledgebase/articles/20 is the proper way ;)
